/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.validation

import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.fML.FMLPackage
import org.xtext.example.mydsl.fML.EditionPattern

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class FMLValidator extends AbstractFMLValidator {

    public static val INVALID_NAME = 'invalidName'
	
	/* 
    @Check
    def checkGreetingStartsWithCapital(EditionPattern editionPattern) {
 		if (!Character::isUpperCase(editionPattern.name.charAt(0))) {
			warning('Name should start with a capital', 
					FMLPackage$Literals::EDITION_PATTERN__NAME,
					INVALID_NAME)
		}
	}*/
}
