/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.xtext.example.mydsl.fML.ViewDef;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to
 * customize content assistant
 */
public class FMLProposalProvider extends
		org.xtext.example.mydsl.ui.contentassist.AbstractFMLProposalProvider {

	@Override
	public void completeViewDef_Name(EObject model, Assignment assignment,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// call implementation of superclass

		super.completeViewDef_Name(model, assignment, context, acceptor);
		ViewDef viewDef = (ViewDef) model;
		String proposal = viewDef.getName() + "ID";
		acceptor.accept(createCompletionProposal(proposal, context));
	}

	@Override
	public void completePatternRole_ModelElement(EObject model,
			Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		
		super.completePatternRole_ModelElement(model, assignment, context, acceptor);
	}

}
